package com.frazao.adubacaodescomplicada.dao.adubacaodescomplicada;

import com.frazao.adubacaodescomplicada.dao.Filtro;
import com.frazao.adubacaodescomplicada.modelo.dto.adubacaodescomplicada.CulturaNecessidadeAduboProducaoFiltroDTO;
import com.frazao.adubacaodescomplicada.modelo.entidade.adubacaodescomplicada.CulturaNecessidadeAduboProducao;

public interface CulturaNecessidadeAduboProducaoDAOFiltro
		extends Filtro<CulturaNecessidadeAduboProducao, CulturaNecessidadeAduboProducaoFiltroDTO> {

}
